name: Deploy
on:
  push:
    branches:
      - main
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: 'Rodcarm/personal-website' # Correct repository reference
          token: ${{ secrets.API_TOKEN_GITHUB }}
          ref: main
          fetch-depth: 0 
          
      - name: Set up Git Configuration
        run: |
          git config --global user.name "Rodrigo" 
          git config --global user.email "rcarmona@realmetrics.io"
      - name: Fetch and Merge Remote Changes
        run: |
          git fetch origin
          git merge origin/main
      - name: Clean and Optimize Git Repository
        run: |
          git gc --prune=now --aggressive
          git repack -a -d --depth=250 --window=250
      - name: Push to gitAccionTest
        run: |
          git push https://${{ secrets.API_TOKEN_GITHUB }}@github.com/Rodcarm/gitActionspersonal-website.git